/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BookingInquiry = IDL.Record({
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllBookingInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitBookingInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BookingInquiry = IDL.Record({
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllBookingInquiries' : IDL.Func(
        [],
        [IDL.Vec(BookingInquiry)],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitBookingInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitTestimonial' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };